name := "SparkMLProject"
version := "1.0"
scalaVersion := "X.XX.X"
libraryDependencies += "org.apache.spark" %% "spark-core" % "Y.Y.Y"
libraryDependencies += "org.apache.spark" %% "spark-mllib" % "Y.Y.Y"
